# Generated by Django 5.2.5 on 2025-12-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="risk_level",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="risk_score",
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="change_1h",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="change_24h",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="change_7d",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="market_cap",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="price_usd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="volume_24h",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="total_value_usd",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="portfolioasset",
            name="allocation_percent",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="portfolioasset",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crmapp.portfolio"
            ),
        ),
    ]
